project_id = "uzcmaxfhfcsxzfqvaloz"

[functions.ai-orchestrator]
verify_jwt = true

[functions.telegram-generate-link-code]
verify_jwt = true

[functions.generate-report]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.sync-storage]
verify_jwt = true

[functions.process-voice]
verify_jwt = true

[functions.process-ocr]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.composite-views-create]
verify_jwt = true

[functions.composite-views-query]
verify_jwt = true

[functions.composite-views-update-custom-data]
verify_jwt = true

[functions.ai-analyze-schema]
verify_jwt = true

[functions.ai-create-schema]
verify_jwt = true

[functions.send-notification]
verify_jwt = true