project_id = "puavudiivxuknvtbnotv"

[functions.ai-orchestrator]
verify_jwt = true

[functions.generate-report]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.sync-storage]
verify_jwt = true

[functions.process-voice]
verify_jwt = true

[functions.process-ocr]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true