# Data Parse Desk 2.0 - Local Development with Docker Compose
# This configuration sets up the complete development environment
# Note: 'version' field is obsolete in Docker Compose v2+

services:
  # ============================================
  # FRONTEND - React Application
  # ============================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dateparsedesk-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_APP_VERSION=2.0.0
      - VITE_APP_ENV=development
    command: npm run dev -- --host 0.0.0.0
    networks:
      - dateparsedesk-network
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # DATABASE - PostgreSQL (Local Supabase)
  # ============================================
  postgres:
    image: supabase/postgres:15.1.0.117
    container_name: dateparsedesk-postgres
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - dateparsedesk-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================
  # SUPABASE STUDIO - Database Management UI
  # ============================================
  studio:
    image: supabase/studio:20231123-64a766a
    container_name: dateparsedesk-studio
    ports:
      - "54323:3000"
    environment:
      SUPABASE_URL: http://kong:8000
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
    networks:
      - dateparsedesk-network
    depends_on:
      - postgres

  # ============================================
  # KONG - API Gateway
  # ============================================
  kong:
    image: kong:2.8.1
    container_name: dateparsedesk-kong
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml
    networks:
      - dateparsedesk-network

  # ============================================
  # REDIS - Caching & Sessions
  # ============================================
  redis:
    image: redis:7-alpine
    container_name: dateparsedesk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dateparsedesk-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================
  # NGINX - Reverse Proxy (Optional)
  # ============================================
  nginx:
    image: nginx:alpine
    container_name: dateparsedesk-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - dateparsedesk-network
    depends_on:
      - frontend
    profiles:
      - production

# ============================================
# NETWORKS
# ============================================
networks:
  dateparsedesk-network:
    driver: bridge

# ============================================
# VOLUMES
# ============================================
volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
